- README.md
- explainer.md
This closes #24 
Please take a look.
> Update the explainer to reflect the new API

- README.md
- explainer.md
- sample-code/basic_usage.html
> Update to the acquire/update/commit api

- README.md
- explainer.md
- sample-code/basic_usage.html
- Rename getDisplayLock to displayLock
- Add a section about updateAndCommit()
> Update display lock docs to the current API

- explainer.md
cc @fergald @vmpstr @chrishtr @domenic
Not sure about the example that I added, also this only adds "activatable", will add contentSize in another PR probably.
> Update explainer with activatable & rewrite some parts

- README.md
cc @fergald @vmpstr @chrishtr @domenic
> Update README with activatability & rewordings

- README.md
> Added a note about display locking availability in Chrome

- explainer-content-size.md
> Add standalone explainer for content-size.

- cheatsheet.md
> Added a cheat-sheet

- cheatsheet.md
> Update cheatsheet with s/visibility/viewport/ activation

- sample-code/tabbed-ui.html
> Updated tabbed-ui example

- sample-code/collapsed-sections.html
> Added a collapsed sections example

- intrinsic-size-security-and-privacy-assessment.md
> Added intrinsic-size security and privacy assessment

- README.md
Added a disclaimer section to the readme pointing to issues and cheatsheet. Also updated various wording to reduce confusion. PTAL.
> Update readme with more correct information

- cheatsheet.md
> Add more explanation to activation scenarios

- index.bs
- index.html
Please take a look. My plan is to have another version for contain-intrinsic-size. The yet-to-be-named event is likely to be a part of the html spec so I'll also add it in some other format.
Let me know if my changes here make sense and whether the plan is fine as well.
> Updated spec

- explainer-beforematch.md
> Added beforematch explainer

- explainer-beforematch.md
> Expanded on the privacy section

- index.bs
- index.html
> Update spec draft title

- explainer-beforematch.md
> Rework the cross-frame privacy interaction.

- README.md
- cheatsheet.md
- explainer-contain-intrinsic-size.md
> rename explainers to subtree-visibility

- contain-intrinsic-size.bs
- contain-intrinsic-size.html
Please take a look
/cc @cbiesinger
> Added spec draft for contain-intrinsic-size

- index.bs
- index.html
> Removed paint containment; reworded containment

- index.bs
- index.html
Please take a look. Rendered output: https://vmpstr.github.io/display-locking/#accessibility
/cc @alice
> Added accessibility section

- index.bs
- index.html
Please take a look. The rendered version should be here: https://vmpstr.github.io/display-locking/#definitions although it hasn't updated for me yet...
> Added definition for subtree

- index.bs
- index.html
Please take a look: https://vmpstr.github.io/display-locking/#subtree-visibility
> Add select and focus to subtree-visibility spec

- index.bs
- index.html
https://vmpstr.github.io/display-locking/index.html#restrictions
Closes #81 
Please take a look.
> Added restrictions and clarifications

- index.bs
- index.html
> Added intersection and resize observer points

- index.bs
- index.html
> specify timing of off-screen values

- index.bs
- index.html
> Added iframe clarification

- index.bs
- index.html
> Clarify innerText behavior.

- index.bs
- index.html
> added paint containment

- explainer-beforematch.md
I made this to address this code review comment: https://chromium-review.googlesource.com/c/chromium/src/+/2068873/21#message-93c7132faae9655a9a22e6b38ed73ff90315d6cb
> Add beforematch scrolling behavior

- explainer-beforematch.md
Addresses https://github.com/WICG/display-locking/issues/160
> Elaborate summary in beforematch explainer

- README.md
> Added a note about screen wake lock api confusion

- explainers/beforematch.md
I made example one more complicated in order to make some points i the alternatives, I hope thats OK
> Add alternatives section to beforematch explainer

- README.md
Signed-off-by: Jens Oliver Meiert <jens@meiert.com>
> chore: fix typos, improve punctuation and formatting

- explainers/content-visibility.md
> Fix markdown syntax

- explainers/beforematch-spec-draft.md
This adds an initial draft of beforematch and hidden-matchable spec
> Beforematch spec draft

- explainers/hidden-content-explainer.md
> Clarify responses to DOM changes in hidden content explainer

- explainers/hidden-content-explainer.md
- Clean up a few things
- Add scroll timing explanation
- Re-add element fragments
- Add element fragment timing issue
- Add accessibility section
- Add mobile device motivation
> Update hidden content explainer
